services:
  flask-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: flask-app:1.0.0
    container_name: flask-container
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    container_name: postgres-container
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"   
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 20s
      retries: 5

volumes:
  pgdata:
    driver: local
