apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "server"
            - "-dev"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: {{ .Values.vault.devRootToken | quote }}
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: {{ .Values.vault.listenAddress | quote }}
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
