# Namespaces with Helm labels
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api
  labels:
    app.kubernetes.io/name: student-api
    app.kubernetes.io/instance: student-api
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
---

# ServiceAccount for ESO with Helm labels
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: service-account
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
---

# ClusterRole for ESO with Helm labels - FIXED RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-cluster-role
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["external-secrets.io"]
    resources: ["secretstores", "clustersecretstores", "externalsecrets", "clusterexternalsecrets", "pushsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets/status", "clusterexternalsecrets/status", "secretstores/status", "clustersecretstores/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---

# ClusterRoleBinding for ESO with Helm labels
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-cluster-role-binding
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-cluster-role
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
---

# Vault token secret with Helm labels - FIXED envsubst syntax
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
type: Opaque
stringData:
  token: ${VAULT_TOKEN}
---

# ESO deployment with Helm labels
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets
  template:
    metadata:
      labels:
        app: external-secrets
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/instance: external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
        - name: external-secrets-operator
          image: ghcr.io/external-secrets/external-secrets:v0.9.9
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-token
                  key: token
---

# ClusterSecretStore pointing to Vault with Helm labels
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault-service.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "external-secrets"
---
# ClusterSecretStore for Vault in observability namespace with Helm labels
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-monitoring
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault-service.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "external-secrets"
---

# ExternalSecret for Student db in student-api namespace with Helm labels
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: studentdb-secrets
  namespace: student-api
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: "vault-backend"
    kind: "ClusterSecretStore"
  target:
    name: "postgres-secret"
    creationPolicy: "Owner"
  data:
    - secretKey: "POSTGRES_USER"
      remoteRef:
        key: "studentdb"
        property: "POSTGRES_USER"
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: "studentdb"
        property: "POSTGRES_PASSWORD"
---
# ExternalSecret for Postgres Exporter in Observability namespace with Helm labels
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-exporter-secret
  namespace: observability
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: "vault-backend-monitoring"
    kind: "ClusterSecretStore"
  target:
    name: "postgres-exporter-secret"
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: postgres-exporter
      property: password
  - secretKey: POSTGRES_USER
    remoteRef:
      key: postgres-exporter
      property: username
  - secretKey: DATA_SOURCE_URI
    remoteRef:
      key: postgres-exporter
      property: connection-uri

---
# ExternalSecret for Grafana Admin in Observability namespace with Helm labels
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: observability
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: "vault-backend-monitoring"
    kind: "ClusterSecretStore"
  target:
    name: "grafana-secret"
  data:
  - secretKey: admin-password
    remoteRef:
      key: grafana
      property: admin-password
  - secretKey: admin-user
    remoteRef:
      key: grafana
      property: admin-user