# Namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---

# ServiceAccount for ESO
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
---

# ClusterRole for ESO - UPDATED WITH MISSING PERMISSIONS
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-cluster-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["external-secrets.io"]
    resources: ["secretstores", "clustersecretstores", "externalsecrets", "clusterexternalsecrets", "pushsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets/status", "clusterexternalsecrets/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---

# ClusterRoleBinding for ESO
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-cluster-role
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
---

# Vault token secret (in external-secrets namespace)
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
stringData:
  token: ${VAULT_TOKEN}
---

# ESO deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator
  namespace: external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets
  template:
    metadata:
      labels:
        app: external-secrets
    spec:
      serviceAccountName: external-secrets
      containers:
        - name: external-secrets-operator
          image: ghcr.io/external-secrets/external-secrets:v0.9.9
          imagePullPolicy: IfNotPresent
---

# ClusterSecretStore pointing to Vault
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault-service.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "external-secrets"

# ClusterSecretStore for Vault in observability namespace
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-monitoring
spec:
  provider:
    vault:
      server: "http://vault-service.vault.svc.cluster.local:8200"
      path: "monitoring"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "external-secrets"
---

# ExternalSecret for Student db in student-api namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: studentdb-secrets
  namespace: student-api
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: "vault-backend"
    kind: "ClusterSecretStore"
  target:
    name: "postgres-secret"
    creationPolicy: "Owner"
  data:
    - secretKey: "POSTGRES_USER"
      remoteRef:
        key: "studentdb"
        property: "POSTGRES_USER"
    - secretKey: "POSTGRES_PASSWORD"
      remoteRef:
        key: "studentdb"
        property: "POSTGRES_PASSWORD"
---
# ExternalSecret for Postgres Exporter in Observability namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-exporter-secret
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: "vault-backend-monitoring"
    kind: "ClusterSecretStore"
  target:
    name: "postgres-exporter-secret"
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: postgres-exporter
      property: password
  - secretKey: POSTGRES_USER
    remoteRef:
      key: postgres-exporter
      property: username
  - secretKey: DATA_SOURCE_URI
    remoteRef:
      key: postgres-exporter
      property: connection-uri

---
# ExternalSecret for Grafana Admin in Observability namespace
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: "vault-backend-monitoring"
    kind: "ClusterSecretStore"
  target:
    name: "grafana-secret"
  data:
  - secretKey: admin-password
    remoteRef:
      key: grafana
      property: admin-password
  - secretKey: admin-user
    remoteRef:
      key: grafana
      property: admin-user