apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
  storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    ui = true
    disable_mlock = true
    storage "file" {
      path = "/vault/data"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    api_addr = "http://vault-service.vault.svc.cluster.local:8200"
    cluster_addr = "https://vault-service.vault.svc.cluster.local:8201"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: vault
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m03
      serviceAccountName: vault
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /vault/data && chown -R 100:1000 /vault/data && chmod -R 755 /vault/data']
        volumeMounts:
        - name: vault-data
          mountPath: /vault/data
        securityContext:
          runAsUser: 0
      containers:
      - name: vault
        image: hashicorp/vault:1.15.0
        command: ["/bin/sh"]
        args:
        - -c
        - |
          cp /vault/config/vault.hcl /tmp/vault.hcl
          exec vault server -config=/tmp/vault.hcl
        ports:
        - containerPort: 8200
          name: http
        env:
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        - name: SKIP_SETCAP
          value: "true"
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 60
          periodSeconds: 30
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
          readOnly: true
        - name: vault-data
          mountPath: /vault/data
        securityContext:
          runAsUser: 100
          runAsGroup: 1000
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
          defaultMode: 0644
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-pvc