namespace: student-api

replicaCount: 2

image:
  repository: akhilthyadi/flask-app
  tag: "7.0.0"
  pullPolicy: IfNotPresent

service:
  name: flask-api-service
  type: NodePort
  port: 80
  targetPort: 5000

config:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "studentdb"

database:
  secretName: postgres-secret
  usernameKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD

nodeSelector:
  type: application
