# Global configuration
global:
  releaseName: student-api
  releaseNamespace: student-api

# Application configuration
app:
  name: flask-api
  image:
    repository: akhilthyadi/flask-app
    tag: "7.0.0"
    pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    name: flask-api-service
    type: NodePort
    port: 80
    targetPort: 5000
  nodeSelector:
    type: application

# Database configuration
database:
  host: "postgres"
  port: "5432"
  name: "studentdb"

# Secret configuration (referencing External Secrets)
secret:
  name: postgres-secret
  userKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD

# ConfigMap configuration
configMap:
  name: flask-config