# Namespace configuration
namespace: student-api

# Flask API image configuration
image:
  repository: akhilthyadi/flask-app
  tag: "7.0.0"
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  name: flask-api
  replicaCount: 2
  labels:
    app: flask-api
  nodeSelector:
    type: application

# Service configuration
service:
  name: flask-api-service
  type: NodePort
  port: 80
  targetPort: 5000

# Configuration
config:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "studentdb"

# ConfigMap reference
configMap:
  name: flask-config
  keys:
    POSTGRES_DB: "POSTGRES_DB"
    POSTGRES_HOST: "POSTGRES_HOST"
    POSTGRES_PORT: "POSTGRES_PORT"

# Secret reference (from External Secrets)
secret:
  name: postgres-secret
  keys:
    POSTGRES_USER: "POSTGRES_USER"
    POSTGRES_PASSWORD: "POSTGRES_PASSWORD"

# Init container configuration
initContainer:
  name: db-migrations
  workingDir: "/api/app"
  env:
    FLASK_APP: "wsgi.py"