apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flask-api.labels" . | nindent 4 }}
data:
  {{ .Values.configMap.keys.POSTGRES_HOST }}: {{ .Values.config.POSTGRES_HOST | quote }}
  {{ .Values.configMap.keys.POSTGRES_PORT }}: {{ .Values.config.POSTGRES_PORT | quote }}
  {{ .Values.configMap.keys.POSTGRES_DB }}: {{ .Values.config.POSTGRES_DB | quote }}