apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.config.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
