namespace: vault

replicaCount: 1

image:
  repository: hashicorp/vault
  tag: "1.17.3"
  pullPolicy: IfNotPresent

service:
  name: vault
  type: ClusterIP
  port: 8200
  targetPort: 8200

vault:
  devRootToken: "root"
  listenAddress: "0.0.0.0:8200"

nodeSelector:
  type: dependent_services
