apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  namespace: {{ .Values.global.releaseNamespace }}
  labels:
    {{- include "postgresql.databaseLabels" . | nindent 4 }}
    app.kubernetes.io/component: database-service
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.database.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
  type: {{ .Values.database.service.type }}