# Global configuration
global:
  releaseName: postgresql
  releaseNamespace: student-api

# Database configuration
database:
  name: postgres
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    name: postgres
    type: ClusterIP
    port: 5432
    targetPort: 5432
  nodeSelector:
    type: database

# Storage configuration
persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: ""  # Use default storage class

# Database configuration
config:
  host: "postgres"
  port: "5432"
  name: "studentdb"

# Secret configuration (referencing External Secrets)
secret:
  name: postgres-secret
  userKey: POSTGRES_USER
  passwordKey: POSTGRES_PASSWORD

# ConfigMap configuration
configMap:
  name: postgres-config