apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secretstore
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.secretName }}
          key: token
          namespace: {{ .Values.namespaces.eso }}
