{{- range .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
    app.kubernetes.io/component: secret-store
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ $.Values.vault.server | quote }}
      path: {{ $.Values.vault.path | quote }}
      version: {{ $.Values.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ $.Values.vaultToken.secretName }}
          key: {{ $.Values.vaultToken.secretKey }}
          namespace: {{ $.Values.namespaces.operator }}
{{- end }}