{{- range $name, $config := .Values.clusterSecretStores }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $name }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
spec:
  provider:
    vault:
      server: "{{ $.Values.vault.server }}"
      path: "{{ $.Values.vault.path }}"
      version: "{{ $.Values.vault.version }}"
      auth:
        tokenSecretRef:
          name: "{{ $.Values.tokenSecret.name }}"
          key: "{{ $.Values.tokenSecret.key }}"
          namespace: "{{ $.Values.namespaces.operator }}"
---
{{- end }}