apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator
  namespace: {{ .Values.namespaces.eso }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: external-secrets
  template:
    metadata:
      labels:
        app: external-secrets
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        type: {{ .Values.nodeSelector.type }}
      containers:
        - name: external-secrets-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
