{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .targetSecret }}
    {{- if .creationPolicy }}
    creationPolicy: {{ .creationPolicy }}
    {{- end }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .vaultKey | quote }}
        property: {{ .vaultProperty | quote }}
    {{- end }}
---
{{- end }}