apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Values.namespaces.app }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.usernameKey }}
      remoteRef:
        key: {{ .Values.database.vaultKey }}
        property: {{ .Values.database.usernameKey }}
    - secretKey: {{ .Values.database.passwordKey }}
      remoteRef:
        key: {{ .Values.database.vaultKey }}
        property: {{ .Values.database.passwordKey }}
