apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tokenSecret.name }}
  namespace: {{ .Values.namespaces.operator }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tokenSecret.key }}: {{ .Values.vault.token | default "" }}