# Namespace configuration
namespaces:
  operator: external-secrets
  application: student-api
  observability: observability

# Operator configuration
operator:
  name: external-secrets-operator
  image: ghcr.io/external-secrets/external-secrets:v0.9.9
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  labels:
    app: external-secrets
  # Configurable resources - can be overridden or set to null to disable
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Service Account configuration
serviceAccount:
  name: external-secrets

# RBAC configuration
rbac:
  clusterRole:
    name: external-secrets-cluster-role
  clusterRoleBinding:
    name: external-secrets-cluster-role-binding

# Vault configuration
vault:
  server: "http://vault-service.vault.svc.cluster.local:8200"
  path: "secret"
  version: "v2"
  # This will be set during deployment
  token: ""

# Token secret configuration
tokenSecret:
  name: vault-token
  key: token

# ClusterSecretStore configuration
clusterSecretStores:
  vault-backend: {}
  vault-backend-monitoring: {}

# ExternalSecret configuration
externalSecrets:
  - name: studentdb-secrets
    namespace: student-api
    refreshInterval: "1h"
    targetSecret: postgres-secret
    creationPolicy: Owner
    secretStore: vault-backend
    data:
      - secretKey: "POSTGRES_USER"
        vaultKey: "studentdb"
        vaultProperty: "POSTGRES_USER"
      - secretKey: "POSTGRES_PASSWORD"
        vaultKey: "studentdb"
        vaultProperty: "POSTGRES_PASSWORD"
  
  - name: postgres-exporter-secret
    namespace: observability
    refreshInterval: "1h"
    targetSecret: postgres-exporter-secret
    secretStore: vault-backend-monitoring
    data:
      - secretKey: POSTGRES_PASSWORD
        vaultKey: postgres-exporter
        vaultProperty: password
      - secretKey: POSTGRES_USER
        vaultKey: postgres-exporter
        vaultProperty: username
      - secretKey: DATA_SOURCE_URI
        vaultKey: postgres-exporter
        vaultProperty: connection-uri

  - name: grafana-secret
    namespace: observability
    refreshInterval: "1h"
    targetSecret: grafana-secret
    secretStore: vault-backend-monitoring
    data:
      - secretKey: admin-password
        vaultKey: grafana
        vaultProperty: admin-password
      - secretKey: admin-user
        vaultKey: grafana
        vaultProperty: admin-user