# Global configuration
global:
  releaseName: external-secrets
  releaseNamespace: external-secrets

# Namespace configuration
namespaces:
  operator: external-secrets
  application: student-api
  observability: observability

# Operator configuration
operator:
  name: external-secrets-operator
  image: ghcr.io/external-secrets/external-secrets
  tag: "v0.9.9"
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  nodeSelector: 
    kubernetes.io/hostname: minikube-m03
  tolerations: []
  affinity: {}

# Service Account configuration
serviceAccount:
  name: external-secrets

# RBAC configuration
rbac:
  clusterRole:
    name: external-secrets-cluster-role
  clusterRoleBinding:
    name: external-secrets-cluster-role-binding

# Vault configuration
vault:
  server: "http://vault-service.vault.svc.cluster.local:8200"
  path: "secret"
  version: "v2"

# Token secret configuration
vaultToken:
  secretName: vault-token
  secretKey: token
  # Set this during deployment: --set vaultToken.value="your-token-here"
  value: ""

# ClusterSecretStore configuration
clusterSecretStores:
  - name: vault-backend
  - name: vault-backend-monitoring

# ExternalSecret configuration
externalSecrets:
  - name: studentdb-secrets
    namespace: student-api
    refreshInterval: "1h"
    targetSecret: postgres-secret
    creationPolicy: Owner
    secretStore: vault-backend
    data:
      - secretKey: "POSTGRES_USER"
        vaultKey: "studentdb"
        vaultProperty: "POSTGRES_USER"
      - secretKey: "POSTGRES_PASSWORD"
        vaultKey: "studentdb"
        vaultProperty: "POSTGRES_PASSWORD"
  
  - name: postgres-exporter-secret
    namespace: observability
    refreshInterval: "1h"
    targetSecret: postgres-exporter-secret
    secretStore: vault-backend-monitoring
    data:
      - secretKey: POSTGRES_PASSWORD
        vaultKey: postgres-exporter
        vaultProperty: password
      - secretKey: POSTGRES_USER
        vaultKey: postgres-exporter
        vaultProperty: username
      - secretKey: DATA_SOURCE_URI
        vaultKey: postgres-exporter
        vaultProperty: connection-uri

  - name: grafana-secret
    namespace: observability
    refreshInterval: "1h"
    targetSecret: grafana-secret
    secretStore: vault-backend-monitoring
    data:
      - secretKey: admin-password
        vaultKey: grafana
        vaultProperty: admin-password
      - secretKey: admin-user
        vaultKey: grafana
        vaultProperty: admin-user