# Namespace configuration
namespaces:
  operator: external-secrets
  application: student-api

# Operator configuration
operator:
  name: external-secrets-operator
  image: ghcr.io/external-secrets/external-secrets:v0.9.9
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  labels:
    app: external-secrets

# Service Account configuration
serviceAccount:
  name: external-secrets

# RBAC configuration
rbac:
  clusterRole:
    name: external-secrets-cluster-role
  clusterRoleBinding:
    name: external-secrets-cluster-role-binding

# Vault configuration
vault:
  server: "http://vault-service.vault.svc.cluster.local:8200"
  path: "secret"
  version: "v2"
  # This will be set during deployment
  token: ""

# Token secret configuration
tokenSecret:
  name: vault-token
  key: token

# ClusterSecretStore configuration
clusterSecretStore:
  name: vault-backend

# ExternalSecret configuration
externalSecrets:
  - name: studentdb-secrets
    namespace: student-api
    refreshInterval: "1h"
    targetSecret: postgres-secret
    creationPolicy: Owner
    data:
      - secretKey: "POSTGRES_USER"
        vaultKey: "studentdb"
        vaultProperty: "POSTGRES_USER"
      - secretKey: "POSTGRES_PASSWORD"
        vaultKey: "studentdb"
        vaultProperty: "POSTGRES_PASSWORD"